# Generated by Django 4.0.3 on 2024-05-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=2)),
                ('birthday', models.IntegerField()),
                ('sex', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=50)),
                ('emailAdd', models.CharField(max_length=30)),
                ('studentId', models.IntegerField()),
                ('course', models.CharField(max_length=30)),
                ('yearLevel', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
