# Generated by Django 4.0.3 on 2024-05-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emailAdd',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('oldStudent', 'Old Student'), ('newStudent', 'New Student'), ('returnee', 'Returnee'), ('transferee', 'Transferee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.IntegerField(unique=True),
        ),
    ]
