# Generated by Django 4.0.3 on 2024-06-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentEntry', '0003_student_image_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(),
        ),
    ]
